title: "Hung-Chieh Wu"
email: hungchieh@psu.edu
description: >-
  Reinforcement Learning and Robotics Researcher. Ph.D. student with expertise
  in quadruped robots, control systems, and machine learning applications.
baseurl: "" # This should match your GitHub repository name
url: "https://hcwu7702.github.io" # Update this to your GitHub Pages URL

# Social media usernames
github_username: hcwu7702

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing
exclude:
  - _site
  - .sass-cache/
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/

# Optional: Enable Markdown options
markdown: kramdown
kramdown:
  input: GFM
